# Generated by Django 3.1.7 on 2021-04-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0003_menuitem_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='extras',
            field=models.CharField(blank=True, help_text="Add extra-paramaters on menu item eg: icon='fa- fa-user'", max_length=255, null=True, verbose_name='extras'),
        ),
    ]
